name: Build & Push Docker Image to ECR

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  ECR_URI: ${{ secrets.ECR_URI }}
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        working-directory: src/backend/CoreAPI
        run: |
          docker build -t ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }} -t ${{ env.ECR_URI }}:${{ github.sha }} .

      - name: Push Docker image tags
        run: |
          docker push ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ECR_URI }}:${{ github.sha }}
