name: Build & Push Docker Image to ECR

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_GITHUB_OIDC_ROLE_ARN: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  ECR_URI: ${{ secrets.ECR_URI }}
  IMAGE_TAG: latest
  DOCKER_CONTAINER: ${{ secrets.DOCKER_CONTAINER }}
  ASPNETCORE_PORT: ${{ secrets.ASPNETCORE_PORT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: src/backend/CoreAPI
        run: |
          docker build -t ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }} -t ${{ env.ECR_URI }}:${{ github.sha }} .

      - name: Push Docker image tags
        run: |
          docker push ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ECR_URI }}:${{ github.sha }}
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
           host: ${{ env.EC2_HOST }}
           username: ${{ env.EC2_USER }}
           key: ${{ env.EC2_SSH_KEY }}
           script: |
             aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
             docker pull ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}
             docker stop ${{ env.DOCKER_CONTAINER }} || true
             docker rm ${{ env.DOCKER_CONTAINER }} || true
             docker run -d --name ${{ env.DOCKER_CONTAINER }} -p 80:${{ env.ASPNETCORE_PORT }} -e ASPNETCORE_URLS="http://+:5130" -e ASPNETCORE_ENVIRONMENT=Development ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}
             docker image prune -f
             
