name: Build & Push Docker Image to ECR

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_GITHUB_OIDC_ROLE_ARN: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
  AWS_SECRETS_MANAGER_SECRET_NAME: ${{ secrets.AWS_SECRETS_MANAGER_SECRET_NAME }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  ECR_URI: ${{ secrets.ECR_URI }}
  IMAGE_TAG: latest
  DOCKER_CONTAINER: ${{ secrets.DOCKER_CONTAINER }}
  ASPNETCORE_PORT: ${{ secrets.ASPNETCORE_PORT }}
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: src/backend/CoreAPI
        run: |
          docker build -t ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }} -t ${{ env.ECR_URI }}:${{ github.sha }} .

      - name: Push Docker image tags
        run: |
          docker push ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ECR_URI }}:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_URI }}
            docker pull ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}
            docker stop ${{ env.DOCKER_CONTAINER }} || true
            docker rm ${{ env.DOCKER_CONTAINER }} || true
            docker run -d --name ${{ env.DOCKER_CONTAINER }} \
            -p 80:${{ env.ASPNETCORE_PORT }} \
            -e ASPNETCORE_URLS="http://+:${{ env.ASPNETCORE_PORT }}" \
            -e ASPNETCORE_ENVIRONMENT=Development \
            -e AWS_REGION=${{ env.AWS_REGION }} \
            -e AWS_SECRETS_MANAGER_SECRET_NAME=${{ env.AWS_SECRETS_MANAGER_SECRET_NAME }} \
            ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}
            docker image prune -f

  migrations:
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        working-directory: src/backend/CoreAPI
        run: dotnet restore

      - name: Restore .NET tools
        working-directory: src/backend/CoreAPI
        run: dotnet tool restore

      - name: Apply Database Migrations
        run: bash scripts/apply_all_migrations.sh
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_SECRETS_MANAGER_SECRET_NAME: ${{ env.AWS_SECRETS_MANAGER_SECRET_NAME }}

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json

      - name: Create frontend env file
        working-directory: src/frontend
        run: |
          echo "VITE_API_URL=https://api.oleksii-andriianenko-agile-app.com/api/v1" > .env.production

      - name: Build react app
        working-directory: src/frontend
        run: |
          npm install
          npm run build:prod

      - name: Sync to s3
        working-directory: src/frontend
        run: |
          aws s3 sync ./dist s3://${{ env.S3_BUCKET_NAME }} --delete